name: DeaDBeeF plugin action build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Package download
      run: sudo apt install libmpg123-dev
    - name: make
      run: make


